name: conekta_tokenizer
description: Flutter plugin that allows you to create credit card tokens using the Conekta payment gateway.
version: 1.0.0
homepage: https://github.com/AgustinV08/conekta_tokenizer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.agustinvillanueva.conekta_tokenizer
        pluginClass: ConektaTokenizerPlugin
      ios:
        pluginClass: ConektaTokenizerPlugin